'use strict'
const { randomUUID }=require('crypto')
class TeamClient{
 constructor(options={}){this.bot=options.bot;this.botId=options.botId;this.botType=options.botType||'official-bot';this.worldId=options.worldId;this.minecraft=options.minecraft;this.registry=options.registry;this.taskManager=options.taskManager;this.skillStats=options.skillStats;this.currentDimension=options.currentDimension;this.inventorySummary=options.inventorySummary;this.safetyState=options.safetyState;this.onPeers=options.onPeers||(()=>{});this.handleControl=options.handleControl||(()=>false);this.heartbeatIntervalMs=options.heartbeatIntervalMs||3000;this.enabled=options.enabled!==false;this.instanceId=randomUUID();this.sockets=new Set();this.pending=new Map();this.activeTeamTask=null;this.activeReservation=false;this.heartbeatTimer=null}
 capabilities(){const names=this.registry.list().map(skill=>skill.name);const aliases={collectWood:'collectWood',collectStone:'mineStone',mineResource:'mineIron',craftTool:'craftBasicItems',craftPlanks:'craftBasicItems',craftCraftingTable:'craftBasicItems',smeltItem:'smeltItems',storeItems:'storeItems',goToLocation:'navigation'};return [...new Set(['navigation',...names.map(name=>aliases[name]||name)])]}
 registration(){return{botId:this.botId,botType:this.botType,instanceId:this.instanceId,worldId:this.worldId,minecraft:{...this.minecraft,dimension:this.currentDimension()},capabilities:this.capabilities(),skillVersions:Object.fromEntries(this.registry.list().map(skill=>[skill.name,String(skill.version||1)])),skills:this.registry.list().map(skill=>({name:skill.name,description:skill.description,version:String(skill.version||1),goals:skill.goals||[]}))}}
 heartbeat(){const local=this.taskManager.status();return{botId:this.botId,instanceId:this.instanceId,worldId:this.worldId,timestamp:Date.now(),state:this.activeTeamTask?'working':local.currentTask?'busy':'idle',position:this.bot.entity?.position?{x:this.bot.entity.position.x,y:this.bot.entity.position.y,z:this.bot.entity.position.z,dimension:this.currentDimension()}:null,health:this.bot.health,food:this.bot.food,currentTaskId:this.activeTeamTask?.id||local.currentTask,currentTeamGoalId:this.activeTeamTask?.teamGoalId||null,currentSkill:local.activeSkill,teamTaskPriority:Number(this.activeTeamTask?.priority||0),teamDestination:this.activeTeamTask?.destination||null,hasObjectReservation:this.activeReservation,inventorySummary:this.inventorySummary(),capabilities:this.capabilities(),skillStats:this.skillStats(),safetyState:this.safetyState(),lastError:local.lastError}}
 attach(socket){if(!this.enabled)return;this.sockets.add(socket);socket.emit('team:register',this.registration());socket.on('team:task-offer',offer=>this.offer(socket,offer));socket.on('team:task-start-approved',payload=>this.start(socket,payload));socket.on('team:task-cancel',payload=>this.cancel(payload));socket.on('team:control',async payload=>{
  try{
   const result=await this.handleControl(String(payload?.action||''),payload||{}),taskId=result?.taskId
   socket.emit('team:control-result',{action:payload?.action,requestId:payload?.requestId,ok:result!==false,taskId,result:result&&typeof result==='object'?{...result,completion:undefined}:undefined})
   // Info: Een geaccepteerde dashboardopdracht is pas klaar wanneer de lokale TaskManager het echte skillresultaat meldt.
   if(taskId!=null){const report=task=>socket.emit('team:control-completed',{action:payload?.action,requestId:payload?.requestId,taskId,ok:task.result?.success===true,errorCode:task.result?.success?null:task.result?.reason||'VALIDATION_FAILED',result:task.result});if(result?.completion)Promise.resolve(result.completion).then(report);else{const listener=task=>{if(task.id!==taskId)return;this.taskManager.off('complete',listener);report(task)};this.taskManager.on('complete',listener)}}
  }catch(error){socket.emit('team:control-result',{action:payload?.action,requestId:payload?.requestId,ok:false,errorCode:error.code||error.message})}
 });socket.on('team:peers',payload=>this.onPeers(Array.isArray(payload?.peers)?payload.peers:[]));socket.on('disconnect',()=>this.sockets.delete(socket));if(!this.heartbeatTimer){this.heartbeatTimer=setInterval(()=>{const payload=this.heartbeat();for(const channel of this.sockets){channel.emit('team:heartbeat',payload);if(this.activeTeamTask)channel.emit('team:task-progress',{taskId:this.activeTeamTask.id,instanceId:this.instanceId,progress:{skill:payload.currentSkill,position:payload.position,updatedAt:Date.now()}})}},this.heartbeatIntervalMs);this.heartbeatTimer.unref?.()}}
 offer(socket,{task}){if(!task||task.worldId!==this.worldId)return socket.emit('team:task-rejected',{taskId:task?.id,instanceId:this.instanceId,reason:'WORLD_MISMATCH'});if(this.activeTeamTask||this.taskManager.active)return socket.emit('team:task-rejected',{taskId:task.id,instanceId:this.instanceId,reason:'TASK_REJECTED'});if(!this.registry.get(task.skill))return socket.emit('team:task-rejected',{taskId:task.id,instanceId:this.instanceId,reason:'CAPABILITY_MISSING'});this.pending.set(task.id,{task,socket});socket.emit('team:task-accepted',{taskId:task.id,instanceId:this.instanceId})}
 async start(socket,{taskId}){const pending=this.pending.get(taskId);if(!pending||this.activeTeamTask)return;this.pending.delete(taskId);const task=pending.task;this.activeTeamTask=task;let reservationId=null;let renewalTimer=null
  try{if(task.destination){const p=task.destination;const containerTask=task.skill==='storeItems';const ttlMs=containerTask?30000:60000;const reservation=containerTask?{type:'object',objectId:`${this.worldId}:container:${p.x}:${p.y}:${p.z}`,worldId:this.worldId,ownerInstanceId:this.instanceId,taskId:task.id,expiresAt:Date.now()+ttlMs}:{type:'area',worldId:this.worldId,ownerInstanceId:this.instanceId,taskId:task.id,bounds:{min:{x:p.x-2,y:p.y-2,z:p.z-2},max:{x:p.x+2,y:p.y+2,z:p.z+2}},expiresAt:Date.now()+ttlMs};const response=await new Promise(resolve=>socket.timeout(3000).emit('team:reservation-create',reservation,(error,value)=>resolve(error?{ok:false,errorCode:'RESERVATION_CONFLICT'}:value)));if(!response?.ok)throw Object.assign(new Error(response?.errorCode||'RESERVATION_CONFLICT'),{code:response?.errorCode});reservationId=response.reservation.id;this.activeReservation=true;renewalTimer=setInterval(()=>socket.emit('team:reservation-renew',{id:reservationId,instanceId:this.instanceId,ttlMs}),Math.max(5000,Math.floor(ttlMs/3)));renewalTimer.unref?.()}
   socket.emit('team:task-started',{taskId:task.id,instanceId:this.instanceId});const completed=new Promise(resolve=>{const listener=local=>{if(local.context?.teamTaskId!==task.id)return;this.taskManager.off('complete',listener);resolve(local)};this.taskManager.on('complete',listener)});this.taskManager.enqueue({name:`team:${task.skill}`,goal:task.teamGoalId,source:'team',priority:Number(task.priority||50)+10,context:{teamTaskId:task.id,target:task.target,destination:task.destination},plan:[{skill:task.skill,context:{target:task.target,destination:task.destination}}]});const local=await completed;if(local.result?.success){if(local.result.data?.container)socket.emit('team:inventory-container',local.result.data.container);socket.emit('team:task-completed',{taskId:task.id,instanceId:this.instanceId,result:local.result})}else if(this.safetyState()==='unsafe')socket.emit('team:task-blocked',{taskId:task.id,instanceId:this.instanceId,errorCode:'UNSAFE_ENVIRONMENT'});else socket.emit('team:task-failed',{taskId:task.id,instanceId:this.instanceId,errorCode:local.result?.reason==='CANCELLED'?'TASK_CANCELLED':local.result?.reason||'VALIDATION_FAILED',context:local.result?.data||{}})
  }catch(error){socket.emit('team:task-failed',{taskId:task.id,instanceId:this.instanceId,errorCode:error.code||error.message||'VALIDATION_FAILED'})}finally{clearInterval(renewalTimer);if(reservationId)socket.emit('team:reservation-release',{id:reservationId,instanceId:this.instanceId});this.activeReservation=false;this.activeTeamTask=null}}
 cancel({taskId}){this.pending.delete(taskId);if(this.activeTeamTask?.id===taskId)this.taskManager.cancelActive('team task cancelled')}
 close(){clearInterval(this.heartbeatTimer);this.heartbeatTimer=null;this.taskManager.cancelActive('team client shutdown');for(const socket of this.sockets)socket.emit('team:unregister',{botId:this.botId,instanceId:this.instanceId});this.sockets.clear()}
}
module.exports={TeamClient}
