const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path')
const {SkillRegistry}=require('../src/skills/skillRegistry');const {TaskManager,PRIORITY}=require('../src/core/taskManager');const result=require('../src/skills/skillResult');const {ErrorCodes}=require('../src/recovery/errorCodes');const validators=require('../src/validation/validators');const {KnowledgeStore,migrate}=require('../src/memory/knowledgeStore');const {ExperienceMemory}=require('../src/memory/experienceMemory');const {SkillStats}=require('../src/learning/skillStats');const {Curriculum}=require('../src/learning/curriculum');const {worldIdentity}=require('../src/memory/worldIdentity');const {WorldMemory}=require('../src/memory/worldMemory')
const {Retrieval}=require('../src/memory/retrieval')
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function registryWith(name,execute,options={}){const registry=new SkillRegistry();registry.register({name,description:name,goals:['goal'],requirements:[],timeoutMs:100,maxRetries:1,execute,validate:c=>c.result,...options});return registry}
function completed(manager){return new Promise(resolve=>manager.once('complete',resolve))}

test('skill registry rejects duplicates and checks requirements',()=>{const r=registryWith('mine',async()=>result.success(),{requirements:['stone_pickaxe']});assert.throws(()=>r.register(r.get('mine')));assert.equal(r.checkRequirements(r.get('mine'),{inventorySummary:{}}).reason,ErrorCodes.REQUIREMENTS_NOT_MET);assert.equal(r.checkRequirements(r.get('mine'),{inventorySummary:{stone_pickaxe:1}}).success,true)})
test('validator proves inventory delta',()=>{let count=1;const bot={inventory:{items:()=>[{name:'iron_ingot',count}]}};assert.equal(validators.itemDelta(bot,'iron_ingot',1,1).success,false);count=2;assert.equal(validators.itemDelta(bot,'iron_ingot',1,1).success,true)})
test('task manager permits one task, prioritizes and preempts',async()=>{const r=registryWith('work',async({signal})=>{await new Promise((resolve,reject)=>{const t=setTimeout(resolve,80);signal.addEventListener('abort',()=>{clearTimeout(t);reject(signal.reason)},{once:true})});return result.success()});const m=new TaskManager({registry:r});const seen=[];m.on('complete',t=>seen.push(t));m.pause();m.enqueue({name:'low',goal:'goal',priority:PRIORITY.EXPLORATION,plan:['work']});m.enqueue({name:'high',goal:'goal',priority:PRIORITY.PLAYER,plan:['work']});m.resume();await wait(200);assert.deepEqual(seen.map(x=>x.name),['high','low']);assert.equal(m.active,null);await m.close()})
test('timeouts cancel work and cleanup abort listeners',async()=>{let aborted=false;const r=registryWith('hang',({signal})=>new Promise(resolve=>signal.addEventListener('abort',()=>{aborted=true;resolve(result.failure(ErrorCodes.CANCELLED))},{once:true})),{timeoutMs:15});const m=new TaskManager({registry:r});const done=completed(m);m.enqueue({goal:'goal',plan:['hang']});const task=await done;assert.equal(task.result.reason,ErrorCodes.TIMEOUT);assert.equal(aborted,true);await m.close()})
test('retry is bounded and receives a changed attempt',async()=>{const attempts=[];const r=registryWith('retry',async c=>{attempts.push(c.attempt);return c.attempt===3?result.success():result.failure(ErrorCodes.PATH_STUCK,true)},{maxRetries:3});const m=new TaskManager({registry:r});const done=completed(m);m.enqueue({goal:'goal',plan:['retry']});const task=await done;assert.equal(task.result.success,true);assert.deepEqual(attempts,[1,2,3]);await m.close()})
test('a successful step continues with every remaining plan step',async()=>{const calls=[],registry=new SkillRegistry();for(const name of ['ensureSafety','buildSchematic'])registry.register({name,requirements:[],timeoutMs:100,maxRetries:1,execute:async()=>{calls.push(name);return result.success({step:name})},validate:c=>c.result});const manager=new TaskManager({registry}),done=completed(manager);manager.enqueue({goal:'build_schematic',plan:['ensureSafety','buildSchematic']});const task=await done;assert.deepEqual(calls,['ensureSafety','buildSchematic']);assert.equal(task.result.data.step,'buildSchematic');await manager.close()})
test('experience deduplicates and stats persist',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'core-memory-'));try{const store=new KnowledgeStore(path.join(root,'learned.json'));const exp=new ExperienceMemory(store,{deduplicationWindowMs:1000});const record={task:'iron',skill:'mine',context:{dimension:'overworld'},success:false,errorCode:'PATH_STUCK',botId:'official-bot',worldId:'w',createdAt:new Date().toISOString()};assert.equal(exp.record(record).stored,true);assert.equal(exp.record(record).stored,false);assert.equal(store.data.experiences.length,1);const stats=new SkillStats(store);stats.record({name:'mine',version:1},result.success({}, {durationMs:20}),{dimension:'overworld'});assert.equal(store.data.skillStats.mine.successRate,1);await store.flush();assert.equal(new KnowledgeStore(path.join(root,'learned.json')).data.skillStats.mine.successes,1)}finally{fs.rmSync(root,{recursive:true,force:true})}})
test('curriculum unlocks only mastered prerequisites',()=>{const stats={move_to_visible_block:{successes:3,successRate:1,lastErrorCodes:[]},collect_wood:{successes:1,successRate:1,lastErrorCodes:[]}};const c=new Curriculum(stats);assert.deepEqual(c.unlocked(),['move_to_visible_block','collect_wood']);assert.equal(c.next(),'collect_wood')})
test('world identity and locations isolate servers',()=>{const a=worldIdentity({host:'a',port:25565,version:'1.21.4'}),b=worldIdentity({host:'b',port:25565,version:'1.21.4'});assert.notEqual(a.worldId,b.worldId);const store={data:{worldLocations:[]},save(){}};const wm=new WorldMemory(store);wm.remember({type:'chest',worldId:a.worldId,dimension:'overworld',position:{x:0,y:1,z:0}});wm.remember({type:'chest',worldId:b.worldId,dimension:'overworld',position:{x:0,y:1,z:0}});assert.equal(store.data.worldLocations.length,2)})
test('schema migration drops invalid record containers',()=>{const value=migrate({schemaVersion:0,experiences:'bad',skillStats:[]});assert.equal(value.schemaVersion,2);assert.deepEqual(value.experiences,[]);assert.deepEqual(value.skillStats,{})})
test('retrieval selects the successful compatible skill',()=>{const registry=new SkillRegistry();for(const name of ['slow','reliable'])registry.register({name,goals:['iron'],requirements:[],execute:async()=>result.success(),validate:c=>c.result});const store={data:{skillStats:{slow:{successRate:.4,averageDurationMs:90000},reliable:{successRate:.9,averageDurationMs:20000}},experiences:[],worldLocations:[]}};assert.equal(new Retrieval(store,registry).getBestSkillForGoal('iron',{}).name,'reliable')})
test('task manager close removes listeners and queued work',async()=>{const manager=new TaskManager({registry:registryWith('work',async()=>result.success())});manager.on('status',()=>{});manager.pause();manager.enqueue({goal:'goal',plan:['work']});await manager.close();assert.equal(manager.queue.length,0);assert.equal(manager.listenerCount('status'),0)})
test('schematic tasks ignore food routines and retain exclusive normal movement',()=>{const source=fs.readFileSync(path.join(__dirname,'..','src','core','legacyBot.js'),'utf8');assert.match(source,/goal === 'build_schematic'/);assert.match(source,/!schematicTaskActive && !state\.hitmanTask && \(bot\.food <= 6 \|\| bot\.health <= 8\)/);assert.match(source,/eliteEmergencySurvival\(\{ ignoreFood:schematicTaskActive \}\)/);assert.match(source,/if \(!schematicTaskActive\) await eatFoodIfNeeded\(\)/);assert.match(source,/if \(reliableTaskActive\) return/);assert.match(source,/skill:'ensureSafety',context:\{ignoreFood:true\}/)})
test('schematic building clears replaceable targets, creates support and reports placement problems',()=>{const source=fs.readFileSync(path.join(__dirname,'..','src','core','legacyBot.js'),'utf8');assert.match(source,/await bot\.dig\(occupied,true\)/);assert.match(source,/buildTemporarySupport/);assert.match(source,/SUPPORT_PLACE_FAILED/);assert.match(source,/PLACE_FAILED/);assert.match(source,/FINAL_WORLD_VALIDATION_FAILED/);assert.match(source,/missingMaterials:missing,problems/);assert.doesNotMatch(source,/placeBlock\([^\n]+\)\}catch\{\}/)})
